### ISSUE TITLE
Confirm macOS support

### ISSUE THREAD

**Issue by clayrisser** [jamrizzi/gtk-node#2]
@nuxlli, would you mind confirming that it still supports mac. Your change broke it on linux, but I fixed it.

**Comment by nuxlli** [comment]
Still working ;)

![screen shot 2017-09-06 at 22 03 48](https://user-images.githubusercontent.com/8738/30141081-558c7c44-934f-11e7-9a91-8fa205db426f.png)

**Comment by clayrisser** [comment]
Niiiice
