### ISSUE TITLE
How high level should node-gtk3 be?

### ISSUE THREAD

**Issue by clayrisser** [jamrizzi/gtk-node#3]
Currently, node-gtk3 is being implemented at a pretty high level. If you look at the current demo, the window is automatically being created and attached to the application. Is this too high level? I want it to be easy to use, but don't want to sacrifice flexibility.

```js
const app = new App({
  title: 'Node Gtk3',
  height: 200,
  width: 200
});
app.run();
```

**Comment by clayrisser** [comment]
@nuxlli @harisvsulaiman @emilioastarita @Place1

**Comment by nuxlli** [comment]
I agree that the level is high.

But as generic as this lib may be, perhaps its api must guide primarily to the use that https://github.com/jamrizzi/react-gtk will make of it.

**Comment by nuxlli** [comment]
For example, I am really impressed with this api and how it can facilitate the creation of a "react-yue": http://libyue.com/docs/v0.1.1/js/

**Comment by clayrisser** [comment]
It's definitely cool. There's already a React Electron. The reason I'm working on React GTK is to create a native React experience for desktop applications. Electron is not native. It's essentially Cordova for desktop.

**Comment by nuxlli** [comment]
Yes I agree.

I found this project just looking for alternatives to this approach. In my searches:

- **qt**: The variety of widgets and helpers is excellent. But licensing has become a problem.

- **efl**: Just as `yue` is simple and light, making it easier to install in different systems. But also a little obscure and little used.

- **gtk+**: Before release of `gtk+3`, it depended on the X11 subsystem, which made its application unattractive on macOS. But now it is more elegant, even if its installation is too complex.

**Comment by clayrisser** [comment]
Getting gtk to work on windows is a little hairy, but it's definitely doable. I successfully got gtk to work on windows in the following repo. I'll definitely use a similar approach when I try and get this to work on windows.

https://github.com/jamrizzi/windows-pygtk

I'm doing all my desktop development with python gtk until I finish this project.

**Comment by harisvsulaiman** [comment]
@jamrizzi @nuxlli I took a different approach here https://github.com/harisvsulaiman/Pushy , instead of building the ui in gjs (or something similar), I used dbus as message passing system to build a hybrid app.
This has both a node js process ( with the business logic ) and native process ( UI stuff ).

This allows me to use this app wherever dbus is available.

**Comment by Place1** [comment]
I'm really excited around all the GTK node bindings so I can potentially hack on a gtk react native.

**Comment by Place1** [comment]
I know this issue is closed, but how about trying to closely follow GJS's GTK bindings?

**Comment by harisvsulaiman** [comment]
@jamrizzi @Place1 @nuxlli Build something that emits Gjs?

**Comment by clayrisser** [comment]
That's a really great idea. I'll make a note on the readme that this project will follow GJS bindings.

**Comment by clayrisser** [comment]
ba3a5d4910bcb79a11bc3fca176233a8acdf41a2
