### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by clayrisser** [jamrizzi/gtk-node#6]
https://github.com/Place1/node-gtk3/commit/22ac86bd40776855b52ce58caa956a9a9d03d875
https://github.com/Place1/node-gtk3/commit/134758b07cb4e590867bd0a97b7c641d4908fb4f

This is were i'm up to. Promises, callbacks, setTimouts etc. all work now, but the program seg faults after a few seconds unfortuantly. I've added some comments on why I think this happens

```
init() {
    loop.startLoop();
    return new Promise((resolve, reject) => {
      // assign the ffi callback to 'this' so we retain a reference
      // after this.init() finishes. If we don't do this Node
      // will garbage collect it and we will get a segmentation
      // fault when C calls into it.
      this.onActivate = ffi.Callback('void', [type.GtkWidgetPtr], (windowPtr) => {
        this.window = new Window({ pointer: windowPtr });
        resolve(this.window);
      });
      app.register_on_activate(this.onActivate);

      // If we call app.init() then it blocks the main loop
      // forever and out program halts.
      // If we call app.init.async() then FFI will call the
      // foreign function in another thread (https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial#async-library-calls)
      // My guess is that it will be scheduled on one of the
      // threads that LibUV controls for IO tasks.
      // This means we avoid blocking the event loop but this
      // results in a segmentation fault after some time and
      // I can't figure out why. My only guess is that it's a
      // multi-thread issue with GTK???
      app.init.async(this.pointer, () => null);
    });
  }
```

**Comment by clayrisser** [comment]
I'm not sure if this is related to it or not, but I noticed the ffi documentation makes an extra reference to the callback pointer on exit.

```js
var ffi = require('ffi');

// Interface into the native lib
var libname = ffi.Library('./libname', {
  'setCallback': ['void', ['pointer']]
});

// Callback from the native lib back into js
var callback = ffi.Callback('void', ['int', 'string'], function(id, name) {
  console.log("id: ", id);
  console.log("name: ", name);
});

console.log("registering the callback");
libname.setCallback(callback);
console.log('done');

// Make an extra reference to the callback pointer to avoid GC
process.on('exit', function() {
  callback
});
```

**Comment by Place1** [comment]
Yeah the segfault isn't from FFI. I fixed that issue by doing this.onActivate = ffi.Callback(...)
Because they 'app' is still referenced it will work.

The seg fault happens anywhere from 3 to 10 seconds after the application window first opening. I think the problem is to do with `app.init.async()`. From the docs, this will schedule the C function on a uv thread (just a normal pthread on linux). My reading on the GTK event loop suggests that this is could be problematic because GTK is not thread safe and so must run all on the same thread. I'd imagine there are various concurrency issues arising from this. The GTK callback for 'activate' would be invoked from the GTK thread (the uv thread from `app.init.async()`) I believe, which could mess up Node, perhaps ffi manages this though and schedules the callback on the eventloop correctly (might have to read up on this). Similarly any ffi calls such as 'button.attach(window)` would violate GTK's thread safety because those GTK api functions would be called from a different thread that where `app.init.async()` scheduled the `g_application_run()`.

**Comment by clayrisser** [comment]
Could you submit a pull request for your fix?

**Comment by Place1** [comment]
I haven't found a fix yet. The work I did on my branch seg faults because i'm still using `app.init.async()`. And if I don't use async, then promises don't resolve (the ffi callbacks run but calling `resolve()` in them does nothing :(`, even with the event loop code (probably buggy or not the right solution).

**Comment by clayrisser** [comment]
"I fixed that issue by doing this.onActivate = ffi.Callback(...)"

**Comment by clayrisser** [comment]
So, we have to somehow interact with GTK in a thread safe way, which ffi doesn't seem to allow?

**Comment by Place1** [comment]
I'm not sure to be honest. Maybe we could experiment by making sure in `attach()` C functions (as an example) we make sure to actually run the GTK api calls on the GTK main loop. I'm not super familiar with GTK but I assume there's a way to make that happen. If that solves some of the crashes then maybe that'll be a good solution? That basically would leave us with 1 main thread for Node's UV loop and another thread for GTK's main loop. And then GTK is providing the currency tools for Node calling GTK.

Node function ---- calls ---> ffi binding --- calls ---> C code --- schedules with GTK main loop ---> GTK api call.

That's adding another overhead though, on top of FFI calls, so it might not be a good solution?

**Comment by clayrisser** [comment]
I just added an extra ref to callbacks on exit, like the ffi docs said to do. I doubt this has anything to do with this issue, but thought I'd give it a try. I've not gotten any segmentation faults yet. How can I reproduce your error?

**Comment by Place1** [comment]
I'm not sure tbh. the seg fault was not from the ffi callback, it was unrelated. I'm speculating it's because of running the g_application_run on another thread but i'm not sure.

**Comment by clayrisser** [comment]
Btw, just thought I'd mention this. When it comes to overhead, we're mostly concerned about rendering overhead. The ffi overhead pales in comparison to rendering overhead.

**Comment by clayrisser** [comment]
This is one of the reasons why this is a much better alternative to electron. Electron does not do native rendering, but this does.

**Comment by clayrisser** [comment]
https://blogs.gnome.org/ebassi/documentation/lazy-loading/

**Comment by clayrisser** [comment]
https://developer.gnome.org/gdk3/stable/gdk3-Threads.html

**Comment by nuxlli** [comment]
Replacing the node's main loop is not trivial and can lead to several problems. I even had commenting on http://libyue.com in issue #3. There are no own cases of a more complex solution: https://github.com/yue/yode

**Comment by clayrisser** [comment]
We're not replacing node's main loop. We're dealing with the gtk thread.

**Comment by clayrisser** [comment]
Ok, I figured out how to multithread gtk. It works so long as you leave the rendering on the same thread.

Look in the multi-threading branch.

https://github.com/jamrizzi/node-gtk3/tree/multi-threading

However, I'm having a race condition problem with the multi-threading right now. I need to figure out how to wait for the render thread to finish before returning the ffi thread. You'll see that it's not rendering the button. I'm pretty sure the following is happening.
```
GTK Main Thread -> App and Window created                                                     -> App Rendered   -> Button added to GTK
FFI Button Thread                        -> Create button called from JS ->  Function returned
```

https://github.com/jamrizzi/node-gtk3/commit/d543dca06bbe4d73136aa2ce65ecbe9956938ab8

**Comment by clayrisser** [comment]
Basically, the app gets rendered before the button is created.  Somehow I need the `attach` function to wait until the button has been attached, rather than returning it immediately after I call ` gdk_threads_add_idle()`.

**Comment by clayrisser** [comment]
The following prints `21`, but it needs to print `12`;

```c
// button/index.c

 gboolean attach_main(gpointer p_package) {                                                                                                                        
   AttachPackage package = *(AttachPackage*)p_package;                                                                                                             
   g_signal_connect(package.button, "clicked", G_CALLBACK(on_click), NULL);                                                                                        
   GtkWidget *button_box;                                                                                                                                          
   button_box = gtk_button_box_new(GTK_ORIENTATION_HORIZONTAL);                                                                                                    
   gtk_container_add(GTK_CONTAINER(package.container), button_box);                                                                                                
   gtk_container_add(GTK_CONTAINER(button_box), package.button);                                                                                                   
+  printf("1");                                                                                                                                                    
   return G_SOURCE_REMOVE;                                                                                                                                         
 }                                                                                                                                                                 
 void attach(GtkWidget *button, GtkWidget *container) {                                                                                                            
   AttachPackage *p_package = g_malloc(sizeof(AttachPackage));                                                                                                     
   p_package->button = button;                                                                                                                                     
   p_package->container = container;                                                                                                                               
   p_package->test = "wow";                                                                                                                                        
   gdk_threads_add_idle(attach_main, p_package);                                                                                                                   
+  printf("2");                                                                                                                                                    
 }
```

**Comment by clayrisser** [comment]
Well, it seems that the solution is to explicitly show the button widget since it gets attached after the main window is rendered.

7093ce8e9810b10489462c055d7001368d327dbe

**Comment by clayrisser** [comment]
Multithreading should be working now. @Place1 let me know if it fixed the segfault issue you were having.

**Comment by clayrisser** [comment]
@Place1 can you confirm if the segfault was fixed for you?

**Comment by Place1** [comment]
Yep all good now!

**Comment by clayrisser** [comment]
Yeeees

**Comment by Place1** [comment]
@jamrizzi can the mutithreading approach lead to developer unfriendly race conditions?

Take this example (not real code)
```
const layout = new Layout()
const button = new Button()
layout.put(button, 0, 0)
console.log('the button is at: ', button.x, button.y)
layout.move(button, 20, 20)
console.log('the button is at: ', button.x, button.y)
```
If the `layout.put()` and `layout.move()` methods aren't actually doing anything but instead enqueing work on the GTK main loop that will do the work, then there is the potential for the `button.x` and `button.y` to not be updated when javascript calls them. A solution for this, would be to make everything that needs to touch GTK go through the gtk main loop in the same way (to ensure concurrency of operations), but would this lead to any significant overheads?
